var annotated_dup =
[
    [ "ant", "namespaceant.html", "namespaceant" ],
    [ "Action", "struct_action.html", "struct_action" ],
    [ "CanvasManager", "class_canvas_manager.html", "class_canvas_manager" ],
    [ "chi2_highscore_t", "structchi2__highscore__t.html", "structchi2__highscore__t" ],
    [ "circit", "classcircit.html", "classcircit" ],
    [ "counts_t", "structcounts__t.html", "structcounts__t" ],
    [ "CutManager", "class_cut_manager.html", "class_cut_manager" ],
    [ "CutStream", "struct_cut_stream.html", "struct_cut_stream" ],
    [ "DrawCanvas", "class_draw_canvas.html", "class_draw_canvas" ],
    [ "DrawCanvas1D", "class_draw_canvas1_d.html", "class_draw_canvas1_d" ],
    [ "DrawCanvas2D", "class_draw_canvas2_d.html", "class_draw_canvas2_d" ],
    [ "EventListManager", "class_event_list_manager.html", "class_event_list_manager" ],
    [ "GunAction", "struct_gun_action.html", "struct_gun_action" ],
    [ "MemtestDummy", "struct_memtest_dummy.html", "struct_memtest_dummy" ],
    [ "MyTInterruptHandler", "class_my_t_interrupt_handler.html", "class_my_t_interrupt_handler" ],
    [ "MyTreeRequestMgr", "class_my_tree_request_mgr.html", "class_my_tree_request_mgr" ],
    [ "padstack", "structpadstack.html", "structpadstack" ],
    [ "PhysicsManagerTester", "struct_physics_manager_tester.html", "struct_physics_manager_tester" ],
    [ "PlutoAction", "struct_pluto_action.html", "struct_pluto_action" ],
    [ "RangeManager", "class_range_manager.html", "class_range_manager" ],
    [ "SavedDirectory_t", "struct_saved_directory__t.html", "struct_saved_directory__t" ],
    [ "SmartTreeImpl", "class_smart_tree_impl.html", "class_smart_tree_impl" ],
    [ "StringColorManager", "class_string_color_manager.html", "class_string_color_manager" ],
    [ "testdata", "structtestdata.html", "structtestdata" ],
    [ "TestPhysics", "struct_test_physics.html", "struct_test_physics" ],
    [ "TitleReset", "struct_title_reset.html", "struct_title_reset" ],
    [ "UndeleteableTLatex", "class_undeleteable_t_latex.html", "class_undeleteable_t_latex" ],
    [ "UpdateableItem", "struct_updateable_item.html", "struct_updateable_item" ]
];